/**
 * test - REST API
 * The REST API provide by the core REST module.
 *
 * The version of the OpenAPI document: Versioning not supported
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://github.com/Backbase/backbase-openapi-tools).
 * https://github.com/Backbase/backbase-openapi-tools
 * Do not edit the class manually.
 */
/**
 * The referenced entity
 */
export interface ModelFile {
    ["target_id"]: number;
    /**
     * Alternative image text, for the image\\\'s \\\'alt\\\' attribute.
     */
    ["alt"]?: string;
    /**
     * Image title text, for the image\\\'s \\\'title\\\' attribute.
     */
    ["title"]?: string;
    /**
     * The width of the image in pixels.
     */
    ["width"]?: number;
    /**
     * The height of the image in pixels.
     */
    ["height"]?: number;
}
