/**
 * test - REST API
 * The REST API provide by the core REST module.
 *
 * The version of the OpenAPI document: Versioning not supported
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://github.com/Backbase/backbase-openapi-tools).
 * https://github.com/Backbase/backbase-openapi-tools
 * Do not edit the class manually.
 */
import { NodeArticleSchemaBody } from './nodeArticleSchemaBody';
import { NodeStatus } from './nodeStatus';
/**
 * Use basic pages for your static content, such as an \\\'About us\\\' page.
 */
export interface NodePageSchema {
    ["promote"]?: Array<NodeStatus>;
    ["body"]?: Array<NodeArticleSchemaBody>;
}
