/**
 * test - REST API
 * The REST API provide by the core REST module.
 *
 * The version of the OpenAPI document: Versioning not supported
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://github.com/Backbase/backbase-openapi-tools).
 * https://github.com/Backbase/backbase-openapi-tools
 * Do not edit the class manually.
 */
import { NodeArticleSchemaBody } from './nodeArticleSchemaBody';
import { NodeArticleSchemaComment } from './nodeArticleSchemaComment';
import { TaxonomyTerm } from './taxonomyTerm';
/**
 * Use articles for time-sensitive content like news, press releases or blog posts.
 */
export interface NodeArticleSchema {
    ["body"]?: Array<NodeArticleSchemaBody>;
    ["comment"]?: Array<NodeArticleSchemaComment>;
    ["field_image"]?: Array<any>;
    /**
     * Enter a comma-separated list. For example: Amsterdam, Mexico City, \\\"Cleveland, Ohio\\\"
     */
    ["field_tags"]?: Array<TaxonomyTerm>;
}
