/**
 * test - REST API
 * The REST API provide by the core REST module.
 *
 * The version of the OpenAPI document: Versioning not supported
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://github.com/Backbase/backbase-openapi-tools).
 * https://github.com/Backbase/backbase-openapi-tools
 * Do not edit the class manually.
 */
import { NodeTitle } from './nodeTitle';
/**
 * Describes the payload for \'node\' entities of the \'image\' bundle.
 */
export interface NodeImageSchema {
    ["title"]: Array<NodeTitle>;
    ["field_image"]?: Array<any>;
}
