/**
 * test - REST API
 * The REST API provide by the core REST module.
 *
 * The version of the OpenAPI document: Versioning not supported
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://github.com/Backbase/backbase-openapi-tools).
 * https://github.com/Backbase/backbase-openapi-tools
 * Do not edit the class manually.
 */
import { NodeTitle } from './nodeTitle';
import { NodeLangcode } from './nodeLangcode';
import { User } from './user';
import { NodeRevisionLog } from './nodeRevisionLog';
import { NodeRevisionTimestamp } from './nodeRevisionTimestamp';
import { NodeUuid } from './nodeUuid';
import { NodeNid } from './nodeNid';
import { NodeType } from './nodeType';
import { NodePath } from './nodePath';
import { NodeStatus } from './nodeStatus';
/**
 * Describes the payload for \'node\' entities.
 */
export interface Node {
    ["nid"]: Array<NodeNid>;
    ["uuid"]: Array<NodeUuid>;
    ["vid"]: Array<NodeNid>;
    ["langcode"]?: Array<NodeLangcode>;
    ["type"]: Array<NodeType>;
    /**
     * The time that the current revision was created.
     */
    ["revision_timestamp"]?: Array<NodeRevisionTimestamp>;
    /**
     * The user ID of the author of the current revision.
     */
    ["revision_uid"]?: Array<User>;
    /**
     * Briefly describe the changes you have made.
     */
    ["revision_log"]?: Array<NodeRevisionLog>;
    ["status"]?: Array<NodeStatus>;
    /**
     * The username of the content author.
     */
    ["uid"]?: Array<User>;
    ["title"]: Array<NodeTitle>;
    /**
     * The time that the node was created.
     */
    ["created"]?: Array<NodeRevisionTimestamp>;
    /**
     * The time that the node was last edited.
     */
    ["changed"]?: Array<NodeRevisionTimestamp>;
    ["promote"]?: Array<NodeStatus>;
    ["sticky"]?: Array<NodeStatus>;
    /**
     * A flag indicating whether this is the default translation.
     */
    ["default_langcode"]?: Array<NodeStatus>;
    /**
     * A flag indicating whether this was a default revision when it was saved.
     */
    ["revision_default"]?: Array<NodeStatus>;
    /**
     * Indicates if the last edit of a translation belongs to current revision.
     */
    ["revision_translation_affected"]: Array<NodeStatus>;
    ["path"]: Array<NodePath>;
}
