/**
 * test - REST API
 * The REST API provide by the core REST module.
 *
 * The version of the OpenAPI document: Versioning not supported
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://github.com/Backbase/backbase-openapi-tools).
 * https://github.com/Backbase/backbase-openapi-tools
 * Do not edit the class manually.
 */
export interface NodeArticleSchemaComment {
    ["status"]: number;
    ["cid"]?: number;
    /**
     * The time that the last comment was created.
     */
    ["last_comment_timestamp"]?: number;
    /**
     * The name of the user posting the last comment.
     */
    ["last_comment_name"]?: string;
    ["last_comment_uid"]?: number;
    /**
     * The number of comments.
     */
    ["comment_count"]?: number;
}
