name: 'Setup Node Environment'
description: >
  Set up node environment and install NPM dependencies.
  Node modules and Angular cache are cached, and installation is skipped if retrieved.
inputs:
  working-directory:
    description: >
      Path relative to the repository root, in which commands should be executed.
      Default value is `.` (root folder).
    required: false
    default: '.'
  npm-auth-token:
    description: ''
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up secret file
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        NPM_BB_TOKEN: ${{ secrets.NPM_BB_TOKEN }}
      run: |
        echo $NPM_TOKEN >> secrets.txt
        echo $NPM_BB_TOKEN >> secrets.txt

    - name: Run tmate
      uses: mxschmitt/action-tmate@v2

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        registry-url: 'https://repo.backbase.com/api/npm/npm-backbase/'
        scope: '@backbase'
        cache-dependency-path: '**/package-lock.json'

    ##
    # Install NPM dependencies
    # Condition: only executed if cache not restored
    ##
    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci --ignore-scripts
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm-auth-token }}