_extends: golden-sample-app:.github/release-drafter.yml
name-template: 'transactions@v$RESOLVED_VERSION'
tag-template: 'transactions@v$RESOLVED_VERSION'
tag-prefix: transactions@v
include-paths:
  - 'libs/transactions/'
