_extends: golden-sample-app:.github/release-drafter.yml
name-template: 'transfer@v$RESOLVED_VERSION'
tag-template: 'transfer@v$RESOLVED_VERSION'
tag-prefix: transfer@v
include-paths:
  - 'libs/transfer/'
