categories:
  - title: 'Features'
    labels: 
      - 'enhancement'
  - title: 'Bug Fixes'
    label: 'bug'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
autolabeler:
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
    body:
      - '/WF-[0-9]{1,4}/'
    - label: 'major'
    title:
      - '/major/i'
    - label: 'minor'
    title:
      - '/minor/i'
    - label: 'patch'
    title:
      - '/patch/i'
      
    
template: |
  ## Changes

  $CHANGES

  ## Contributors

  Thanks to $CONTRIBUTORS for your contributions to this release!
