version: "3"

services:
  web:
    build:
      context: .
    ports:
      - target: 4200
        published: 4200
    environment:
      PROTOCOL: 'http:'
      HOSTNAME: localhost
      PORT: 4200
      BASE_HREF: /
      API_ROOT: https://app.prd.sdbxaz.azure.backbaseservices.com/api
      AUTH_URL: https://identity.prd.sdbxaz.azure.backbaseservices.com/auth/realms/customer
      AUTH_SCOPE: openid profile email
      AUTH_CLIENT_ID: bb-web-client
      LOCALES: en,nl
      FALLBACK_LOCALE: nl
