version: "3"

services:
  web:
    build:
      context: .
    ports:
      - target: 4200
        published: 4200
    environment:
      PROTOCOL: 'http:'
      HOSTNAME: localhost
      PORT: 4200
      BASE_HREF: /golden-sample/
      API_ROOT: https://app.prd.sdbx.live.backbaseservices.com/api
      AUTH_URL: https://identity.prd.sdbx.live.backbaseservices.com/auth
      AUTH_SCOPE: openid profile email
      AUTH_CLIENT_ID: bb-web-client
      AUTH_LANDING_PAGE: transactions
      AUTH_REDIRECT_PAGE: login
      LOCALES: en,nl
