name: Bump Version

description: Version affected packages

inputs:
  github_token:
    description: GitHub token
    required: true
  npm_token:
    description: NPM token
    required: true
runs:
  using: composite
  steps: 
    - name: install dependencies
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm_token }}
      shell: bash
      run: npm ci --legacy-peer-deps

    - name: Setup git user to "GSA Bot"
      shell: bash
      run: git config user.email "-" && git config user.name "🤖 GSA Bot"

    - name: Version
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm_token }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
      shell: bash
      run: npx nx affected --base= origin/main~1 --head= HEAD --parallel=1 --target=version

    - name: Tag last-release
      shell: bash
      run: git tag -f last-release

    # - name: Push changes
    #   uses: ad-m/github-push-action@master
    #   with:
    #     github_token: ${{ inputs.github_token }}
    #     branch: ${{ github.ref }}
    #     force: true
    #     tags: true
