/**
 * Wordpress v2 API
 * Wordpress v2 API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://github.com/Backbase/backbase-openapi-tools).
 * https://github.com/Backbase/backbase-openapi-tools
 * Do not edit the class manually.
 */
export interface CommonPostPage {
    /**
     * The date the object was published, in the site\'s timezone.
     */
    ["date"]?: string;
    /**
     * The date the object was published, as GMT.
     */
    ["date_gmt"]?: string;
    /**
     * The globally unique identifier for the object.
     */
    ["guid"]?: string;
    /**
     * Unique identifier for the object.
     */
    ["id"]?: number;
    /**
     * URL to the object.
     */
    ["link"]?: string;
    /**
     * The date the object was last modified, in the site\'s timezone.
     */
    ["modified"]?: string;
    /**
     * The date the object was last modified, as GMT.
     */
    ["modified_gmt"]?: string;
    /**
     * The A password to protect access to the post.
     */
    ["password"]?: string;
    /**
     * An alphanumeric identifier for the object unique to its type.
     */
    ["slug"]?: string;
    /**
     * A named status for the object.
     */
    ["status"]?: CommonPostPage.StatusEnum;
    /**
     * Type of Post for the object.
     */
    ["type"]?: string;
    /**
     * The title for the object.
     */
    ["title"]?: string;
    /**
     * The content for the object.
     */
    ["content"]?: string;
    /**
     * The id for the author of the object.
     */
    ["author"]?: string;
    /**
     * The excerpt for the object
     */
    ["excerpt"]?: string;
    /**
     * The id of the featured media for the object.
     */
    ["featured_media"]?: string;
    /**
     * Whether or not comments are open on the object
     */
    ["comment_status"]?: CommonPostPage.CommentStatusEnum;
    /**
     * Whether or not the object can be pinged.
     */
    ["ping_status"]?: CommonPostPage.PingStatusEnum;
}
export declare namespace CommonPostPage {
    type StatusEnum = 'publish' | 'future' | 'draft' | 'pending' | 'private';
    const StatusEnum: {
        Publish: StatusEnum;
        Future: StatusEnum;
        Draft: StatusEnum;
        Pending: StatusEnum;
        Private: StatusEnum;
    };
    type CommentStatusEnum = 'open' | 'closed';
    const CommentStatusEnum: {
        Open: CommentStatusEnum;
        Closed: CommentStatusEnum;
    };
    type PingStatusEnum = 'open' | 'closed';
    const PingStatusEnum: {
        Open: CommentStatusEnum;
        Closed: CommentStatusEnum;
    };
}
