/**
 * Wordpress v2 API
 * Wordpress v2 API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://github.com/Backbase/backbase-openapi-tools).
 * https://github.com/Backbase/backbase-openapi-tools
 * Do not edit the class manually.
 */
export interface PageAllOf {
    /**
     * The id for the parent of the object.
     */
    ["parent"]?: number;
    /**
     * The order of the object in relation to other object of its type.
     */
    ["menu_order"]?: number;
    /**
     * The theme file to use to display the object.
     */
    ["template"]?: number;
}
