name: Auto-generate PR from Issues using Aider
on:
  issues:
    types: [labeled]

jobs:
  generate:
    permissions:
      issues: read
      pull-requests: write
      contents: write
    uses: ./.github/workflows/aider-issue-to-pr.yml
    # Check if the label is 'aider'
    if: github.event.label.name == 'aider'
    with:
      issue-number: ${{ github.event.issue.number }}
      base-branch: ${{ github.event.repository.default_branch }}
    secrets: 
      anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
