name: CI

on:
  push:
    branches:
      - WF-868-implement-tasks-whenever-a-release-workflow-is-triggered

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          registry-url: 'https://repo.backbase.com/artifactory/api/npm/npm-backbase/'
          scope: '@backbase'   
      - name: Release
        uses: ./.github/actions/bump-version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          npm_token: ${{ secrets.NPM_TOKEN }}