name: E2E Tests

on:
  pull_request:
    branches:
      - main
jobs:
  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.25.0-focal

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          registry-url: 'https://repo.backbase.com/artifactory/api/npm/npm-backbase/'
          scope: '@backbase'

      - name: Install Dependencies
        run: npm ci --legacy-peer-deps
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Run Playwright tests
        run: npm run e2e