# Controls when the action will run. The workflow runs when manually triggered using the UI or API

name: Foundation_Ang_On_Demand

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      foundation_ang_version:
        description: 'Foundation-ang version'
        required: true
        default: '7.0.0'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_web:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: ${{ github.base_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          registry-url: 'https://repo.backbase.com/artifactory/api/npm/npm-backbase/'
          scope: '@backbase'

      - name: Install Foundation-ang
        run: npm install @backbase/foundation-ang@${{ github.event.inputs.foundation_ang_version }}

      - name: Build app
        run: npm run affected:build

      - name: Unit test
        run: npm run affected:test
