name: Update Angular tag

on:
  push:
    branches:
      - test/angular-v12

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: Get Angular version
        id: get-angular-version
        run: |
          version=$(node -p "require('./package-lock.json').dependencies['@angular/core'].version.split('.').shift()")
          echo "::set-output name=version::$version"

      - name: Update tag
        run: |
          tag='angular@v${{ steps.get-angular-version.outputs.version }}'
          git tag $tag -f
          git push origin $tag -f
